# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bE22bANZyC3OuVZFCGdK3kyhYDwUcuvh
"""

import streamlit as st

st.title("Mi primera app")
st.text("Autor: Esta app fue elaborada por 'Felipe Velez Fernandez'")

nombre_usuario = st.text_input("Por favor, introduce tu nombre:")
mensaje_bienvenida = f"{nombre_usuario}, te doy la bienvenida a mi primera app."

st.write(mensaje_bienvenida)

